---
- name: My Test Playbook
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: installed
      notify: start apache

    - name: start httpd service
      service:
        name: httpd
        state: started
