---
- name: My Test Playbook
  hosts: all
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: installed
    - name: httpd Service Start
      service:
        name: httpd
        state: started
