---
- name: This playbook install httpd package
  hosts: all
  become: yes
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Start httpd Service
      service:
        name: http---
        state: started
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Install Apache Package
      apt:
        name: apache2
        state: Present
      when: ansible_os_family == "Debian"

    - name: Start Apache Service
      apt:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: copy index.html
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html
        mode: '0666'
