---
- name: My Test Playbook
  hosts: all
  become: yes
  tasks:
    - name: Stop the httpd service
      service:
        name: httpd
        state: stopped

    - name: remove httpd package
      yum:
        name: httpd
        state: removed
